version: '3.9'

services:
  billing:
    build: ./billing
    expose:
      - "8000"
    ports:
      - "8000:8000"
    env_file:
      - ./env_files/billing.env
    networks:
      - history_net
    healthcheck:
      test: curl --fail http://billing:8000/api/health/ || exit 1
      interval: 10s
      timeout: 5s
      retries: 20
    depends_on:
      payment_db:
        condition: service_healthy

  payment_db:
    image: postgres:15.0-alpine
    expose:
      - "5432"
    networks:
      - history_net
    environment:
      - POSTGRES_HOST=payment_db
      - POSTGRES_PORT=5432
    volumes:
      - payment_vol:/var/lib/postgresql/data/
      - ./payment_db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
    env_file:
      - env_files/payment_db.env
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -d $$POSTGRES_DB -h $$POSTGRES_HOST -p $$POSTGRES_PORT -U $$POSTGRES_USER"
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  admin_panel:
    build: admin_panel
    volumes:
      - static_data:/opt/app/static/
    env_file:
      - env_files/admin.env
    expose:
      - "8000"
    networks:
      - history_net
    depends_on:
      payment_db:
        condition: service_healthy

  scheduler:
    build: ./scheduler
    networks:
      - history_net
    env_file:
      - ./env_files/scheduler.env
    depends_on:
      - payment_db

networks:
  history_net:


volumes:
  static_data:
  payment_vol:
