version: '3.9'

services:
  billing:
    build: ./billing
    expose:
      - "8000"
    env_file:
      - ./env_files/billing.env
    healthcheck:
      test: curl --fail http://billing:8000/api/health/ || exit 1
      interval: 10s
      timeout: 5s
      retries: 20

  payment_db:
    image: postgres:15.0-alpine
    expose:
      - "5432"
    networks:
      - history_net
    volumes:
      - ./payment_db_init:/docker-entrypoint-initdb.d:ro
    env_file:
      - env_files/pyment_db.env
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -d $$POSTGRES_DB -h $$POSTGRES_HOST -p $$POSTGRES_PORT -U $$POSTGRES_USER"
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  scheduler:
    build: ./scheduler
    networks:
      - history_net
    env_file:
      - ./env_files/scheduler.env
    depends_on:
      - payment_db

networks:
  history_net:
