# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import enum_type_wrapper

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\nauth.proto"\x12\n\x10UsersDataRequest"T\n\x11UsersDataResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x11\n\ttelephone\x18\x04 \x01(\t"\x1c\n\x08UsersIds\x12\x10\n\x08list_ids\x18\x01 \x01(\t"2\n\x11\x43hangeRoleRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0c\n\x04role\x18\x02 \x01(\t"7\n\x12\x43hangeRoleResponse\x12!\n\x06status\x18\x01 \x01(\x0e\x32\x11.ResponseStatuses*#\n\x10ResponseStatuses\x12\x07\n\x03\x42\x41\x44\x10\x00\x12\x06\n\x02OK\x10\x01\x32\xbd\x01\n\nAuthNotify\x12\x38\n\x0bGetUserData\x12\x11.UsersDataRequest\x1a\x12.UsersDataResponse"\x00\x30\x01\x12;\n\x16GetUserDataFromUsersId\x12\t.UsersIds\x1a\x12.UsersDataResponse"\x00\x30\x01\x12\x38\n\x0bSetUserRole\x12\x12.ChangeRoleRequest\x1a\x13.ChangeRoleResponse"\x00\x62\x06proto3'
)

_RESPONSESTATUSES = DESCRIPTOR.enum_types_by_name["ResponseStatuses"]
ResponseStatuses = enum_type_wrapper.EnumTypeWrapper(_RESPONSESTATUSES)
BAD = 0
OK = 1


_USERSDATAREQUEST = DESCRIPTOR.message_types_by_name["UsersDataRequest"]
_USERSDATARESPONSE = DESCRIPTOR.message_types_by_name["UsersDataResponse"]
_USERSIDS = DESCRIPTOR.message_types_by_name["UsersIds"]
_CHANGEROLEREQUEST = DESCRIPTOR.message_types_by_name["ChangeRoleRequest"]
_CHANGEROLERESPONSE = DESCRIPTOR.message_types_by_name["ChangeRoleResponse"]
UsersDataRequest = _reflection.GeneratedProtocolMessageType(
    "UsersDataRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _USERSDATAREQUEST,
        "__module__": "auth_pb2"
        # @@protoc_insertion_point(class_scope:UsersDataRequest)
    },
)
_sym_db.RegisterMessage(UsersDataRequest)

UsersDataResponse = _reflection.GeneratedProtocolMessageType(
    "UsersDataResponse",
    (_message.Message,),
    {
        "DESCRIPTOR": _USERSDATARESPONSE,
        "__module__": "auth_pb2"
        # @@protoc_insertion_point(class_scope:UsersDataResponse)
    },
)
_sym_db.RegisterMessage(UsersDataResponse)

UsersIds = _reflection.GeneratedProtocolMessageType(
    "UsersIds",
    (_message.Message,),
    {
        "DESCRIPTOR": _USERSIDS,
        "__module__": "auth_pb2"
        # @@protoc_insertion_point(class_scope:UsersIds)
    },
)
_sym_db.RegisterMessage(UsersIds)

ChangeRoleRequest = _reflection.GeneratedProtocolMessageType(
    "ChangeRoleRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _CHANGEROLEREQUEST,
        "__module__": "auth_pb2"
        # @@protoc_insertion_point(class_scope:ChangeRoleRequest)
    },
)
_sym_db.RegisterMessage(ChangeRoleRequest)

ChangeRoleResponse = _reflection.GeneratedProtocolMessageType(
    "ChangeRoleResponse",
    (_message.Message,),
    {
        "DESCRIPTOR": _CHANGEROLERESPONSE,
        "__module__": "auth_pb2"
        # @@protoc_insertion_point(class_scope:ChangeRoleResponse)
    },
)
_sym_db.RegisterMessage(ChangeRoleResponse)

_AUTHNOTIFY = DESCRIPTOR.services_by_name["AuthNotify"]
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _RESPONSESTATUSES._serialized_start = 259
    _RESPONSESTATUSES._serialized_end = 294
    _USERSDATAREQUEST._serialized_start = 14
    _USERSDATAREQUEST._serialized_end = 32
    _USERSDATARESPONSE._serialized_start = 34
    _USERSDATARESPONSE._serialized_end = 118
    _USERSIDS._serialized_start = 120
    _USERSIDS._serialized_end = 148
    _CHANGEROLEREQUEST._serialized_start = 150
    _CHANGEROLEREQUEST._serialized_end = 200
    _CHANGEROLERESPONSE._serialized_start = 202
    _CHANGEROLERESPONSE._serialized_end = 257
    _AUTHNOTIFY._serialized_start = 297
    _AUTHNOTIFY._serialized_end = 486
# @@protoc_insertion_point(module_scope)
