name: CI

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  flake:
    name: Flake8
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.8

      - name: Create directories
        run: |
          mkdir -p reports/flake8/
      - name: Installing dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wemake-python-styleguide==0.17.0 flake8-quotes==3.3.1 flake8-html

      - name: Setup flake8 annotations
        uses: rbialon/flake8-annotations@v1.1

      - name: Flake8 check UGC API
        run: flake8 --config=.flake8

  black:
    name: Black
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable
        with:
          options: "--check --verbose"
          jupyter: true

  hadolint:
    name: Hadolint
    runs-on: ubuntu-latest
    env:
      HADOLINT_RECURSIVE: "true"
    steps:
      - uses: actions/checkout@v3

      - name: Run Hadolint
        uses: hadolint/hadolint-action@v3.0.0
        with:
          recursive: true

  mypy:
    name: Mypy python-${{ matrix.python-version }} type checking
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.8

      - name: pip upgrade
        run: |
          python -m pip install --upgrade pip
      - name: Installing mypy
        run: |
          python -m pip install mypy types-protobuf

      - name: Add mypy annotator
        uses: pr-annotators/mypy-pr-annotator@v1.0.0

      - name: mypy with python-version ${{ matrix.python-version }}
        run: mypy --config=pyproject.toml --python-version ${{ matrix.python-version }}

  telegram_message:
    name: Send message to telegram
    runs-on: ubuntu-latest
    needs: [flake, black, hadolint, mypy]
    steps:
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.actor }} открыл новый pull request:
            ${{ github.event.pull_request.title }}

            Призываю проверить:
            https://github.com/${{ github.repository }}/pull/${{ github.event.pull_request.number }}

            Так же можно проверить остальные ПР:
            https://github.com/${{ github.repository }}/pulls
